### PR TITLE
Fix out-of-sync binding names causing null ref error

### LINKED ISSUE #210: Cannot read properties of undefined (reading 'type')
#### Investigative information

Please provide the following:

- Timestamp: 2024-01-22T22:14:28.4980344Z
- Function App name: AZUD-RMS-FA-01
- Function name(s) (as appropriate): customerLookup
- Invocation ID: 3325acd5-1aad-4923-bffc-0a6fbfe52204
- Region: East US 2

#### Repro steps

Provide the steps required to reproduce the problem:

1. Open `https://azud-rms-fa-01.azurewebsites.net/api/v4/customer?emailAddress=lightspeed.e2e%40gmail.com` in a browser

#### Expected behavior

Provide a description of the expected behavior.

Http request should return valid JSON and 200 response

#### Actual behavior

500 error

#### Related information 

Provide any related information 

* Programming language used: javascript
* Bindings used:

```ts
app.get("customerLookup", {
  authLevel: "anonymous",
  route: `api/v{version:int:min(4):max(${currentMajorVersion})}/customer`,
  handler,
});
```

* Stack Trace:
```
Stack: TypeError: Cannot read properties of undefined (reading 'type')
    at InvocationModel.<anonymous> (/node_modules/@azure/functions/dist/webpack:/@azure/functions/src/InvocationModel.ts:65:63)
    at Generator.next (<anonymous>)
    at <anonymous> (/node_modules/@azure/functions/dist/webpack:/@azure/functions/src/InvocationContext.ts:96:10)
    at new Promise (<anonymous>)
    at __webpack_modules__../src/InvocationModel.ts.__awaiter (/node_modules/@azure/functions/dist/webpack:/@azure/functions/src/InvocationContext.ts:96:10)
    at InvocationModel.getArguments (/node_modules/@azure/functions/dist/webpack:/@azure/functions/src/InvocationModel.ts:46:23)
    at y.<anonymous> (/azure-functions-host/workers/node/dist/src/worker-bundle.js:2:37611)
    at Generator.next (<anonymous>)
    at o (/azure-functions-host/workers/node/dist/src/worker-bundle.js:2:35629)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

This error is not reproducible locally, only on our Azure instance. While it is reproducible for a single function run, restarting the function will fix the issue.

Relevant code appears to be here:

https://github.com/Azure/azure-functions-nodejs-library/blob/aa9068df56c2d4c2b90ee55dd42005e1d7c5cb4c/src/InvocationModel.ts#L46-L79

### PR DESCRIPTION
**Pull request by ejizba**
Fixes https://github.com/Azure/azure-functions-nodejs-library/issues/210

The logs from the user indicate a mismatch in the binding name between the host and worker ("httpTrigger17" vs "httpTrigger19"). I suspect our logic in "addBindingName" isn't reliable enough at returning the same binding name. When I first adjusted the logic in "addBindingName" (see [the original issue](https://github.com/Azure/azure-functions-nodejs-worker/issues/638)) I thought the problem only repro-ed with multiple workers in parallel, but now I think it can also happen with multiple workers in serial (aka a worker restarts, but the host stays the same). Fwiw, I checked telemetry and only a handful of apps are hitting this issue, but I definitely don't want anyone to hit this at all.

Anyways, my new solution is to create a hash of the binding configuration, which should reliably create the same binding name each time and also be unique within the function (we need name uniqueness at the function level, but not the app level). The only way we could get conflicting names is if they register bindings with the exact same config within a single function, but I have no idea why someone would do that. Regardless, I added an error up front so that it will fail-fast if they're in that situation and be easy for them to fix.

Lastly, I split this PR into two commits for easier review:
- The first moves code to a new file with no functional changes: https://github.com/Azure/azure-functions-nodejs-library/commit/2e24f147ac5a04243c2f5502f48a09aa138da5bf
- The second actually fixes the issue: https://github.com/Azure/azure-functions-nodejs-library/commit/2f08eb60776485200d678a5725667daca5baeb14

### CODE REVIEW

File: src/converters/toCoreFunctionMetadata.ts [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+                direction: 'out',
+            };
+            bindingNames.push(output.name);
+        }
+    }
+
+    const dupeBindings = bindingNames.filter((v, i) => bindingNames.indexOf(v) !== i);
+    if (dupeBindings.length > 0) {
+        throw new AzFuncSystemError(
+            `Duplicate bindings found for function "${name}". Remove a duplicate binding or manually specify the "name" property to make it unique.`
```
Comment (castrodd) [inline src/converters/toCoreFunctionMetadata.ts:54]: Should we capture the duplicate binding's name and log in this error message? Or is the number of bindings so small that the user can figure it out without the information?

**Review by castrodd — APPROVED** [review]

File: src/converters/toCoreFunctionMetadata.ts (hunk 1 above)
Comment (ejizba) [reply src/converters/toCoreFunctionMetadata.ts:54]: The name is auto-generated, so it probably own't mean much to the user. And yeah I would expect most functions have 1-3 bindings, with anything more than 5 to be abnormally high
